/*
  File autogenerated by gengetopt version 2.22.6
  generated with the following command:
  gengetopt -u

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef FIX_UNUSED
#define FIX_UNUSED(X) (void) (X) /* avoid warnings for unused params */
#endif

#include <getopt.h>

#include "cmdline.h"

const char *gengetopt_args_info_purpose = "NGSfold: Improving RNA secondary structure prediction with weak label learning\nfrom NGS data.";

const char *gengetopt_args_info_usage = "Usage: ngsfold [OPTIONS]";

const char *gengetopt_args_info_versiontext = "";

const char *gengetopt_args_info_description = "";

const char *gengetopt_args_info_full_help[] = {
  "  -h, --help                    Print help and exit",
  "      --full-help               Print help, including hidden options, and exit",
  "  -V, --version                 Print version and exit",
  "      --noncomplementary        Allow non-canonical base pairs  (default=off)",
  "  -p, --param=parameter-file    Load parameters from parameter-file",
  "      --random-seed=INT         Specify the seed of the random number generator\n                                  (default=`-1')",
  "      --max-span=INT            The maximum distance between bases of base\n                                  pairs  (default=`-1')",
  "  -v, --verbose=INT             Verbose output  (default=`0')",
  "\nPrediction mode:",
  "      --predict                 Prediction mode  (default=on)",
  "      --mea=gamma               MEA decoding with gamma  (default=`6.0')",
  "  -g, --gce=gamma               Generalized centroid decoding with gamma\n                                  (default=`4.0')",
  "      --bpseq                   Output predicted results as the BPSEQ format\n                                  (default=off)",
  "      --constraints             Use contraints  (default=off)",
  "\nTraining mode:",
  "      --train=output-file       Trainining mode (write the trained parameters\n                                  into output-file)",
  "  -i, --max-iter=INT            The maximum number of iterations for training\n                                  (default=`100')",
  "  -b, --burn-in=INT             The number of iterations for initial training\n                                  from labeled data  (default=`10')",
  "      --weight-weak-label=FLOAT The weight for weak labeled data\n                                  (default=`0.1')",
  "  -T, --structure=filename-list The lists of training data with full structures",
  "  -U, --unpaired-reactivity=filename-list\n                                The lists of training data with unpaired\n                                  reactivity",
  "  -P, --paired-reactivity=filename-list\n                                The lists of training data with paired\n                                  reactivity",
  "  -B, --both-reactivity=filename-list\n                                The lists of training data with both of\n                                  unpaired and paired  reactivity",
  "      --eta=FLOAT               Initial step width of the subgradient\n                                  optimization  (default=`1.0')",
  "      --eta-weak-label=FLOAT    Initial step width of the subgradient\n                                  optimization for weak labeled data\n                                  (default=`0.1')",
  "      --pos-w=FLOAT             The weight for positive base-pairs\n                                  (default=`8')",
  "      --neg-w=FLOAT             The weight for negative base-pairs\n                                  (default=`1')",
  "      --pos-w-unpaired=FLOAT    The weight for positive base-pairs for training\n                                  from unpaired reactivity data  (default=`0')",
  "      --neg-w-unpaired=FLOAT    The weight for negative base-pairs for training\n                                  from unpaired reactivity data  (default=`0')",
  "      --per-bp-loss             Ajust the loss according to the number of base\n                                  pairs  (default=off)",
  "      --lambda=FLOAT            The weight for the L1 regularization term\n                                  (default=`0.0001')",
  "      --scale-reactivity=FLOAT  The scale of reactivity  (default=`1.0')",
  "      --threshold-unpaired-reactivity=FLOAT\n                                The threshold of reactiviy for unpaired bases\n                                  (default=`0.0')",
  "      --threshold-paired-reactivity=FLOAT\n                                The threshold of reactiviy for paired bases\n                                  (default=`0.0')",
  "      --discretize-reactivity   Discretize reactivity with reactivity\n                                  thresholds  (default=off)",
  "      --bp-context              Train the features for base-pair contexts in\n                                  weak label traing   (default=off)",
  "      --out-param=dirname       Output parameter sets for each step",
  "\nValidation mode:",
  "      --validate                Validation mode: validate the given structure\n                                  can be parsed  (default=off)",
    0
};

static void
init_help_array(void)
{
  gengetopt_args_info_help[0] = gengetopt_args_info_full_help[0];
  gengetopt_args_info_help[1] = gengetopt_args_info_full_help[1];
  gengetopt_args_info_help[2] = gengetopt_args_info_full_help[2];
  gengetopt_args_info_help[3] = gengetopt_args_info_full_help[3];
  gengetopt_args_info_help[4] = gengetopt_args_info_full_help[4];
  gengetopt_args_info_help[5] = gengetopt_args_info_full_help[5];
  gengetopt_args_info_help[6] = gengetopt_args_info_full_help[6];
  gengetopt_args_info_help[7] = gengetopt_args_info_full_help[7];
  gengetopt_args_info_help[8] = gengetopt_args_info_full_help[8];
  gengetopt_args_info_help[9] = gengetopt_args_info_full_help[9];
  gengetopt_args_info_help[10] = gengetopt_args_info_full_help[10];
  gengetopt_args_info_help[11] = gengetopt_args_info_full_help[11];
  gengetopt_args_info_help[12] = gengetopt_args_info_full_help[12];
  gengetopt_args_info_help[13] = gengetopt_args_info_full_help[13];
  gengetopt_args_info_help[14] = gengetopt_args_info_full_help[14];
  gengetopt_args_info_help[15] = gengetopt_args_info_full_help[15];
  gengetopt_args_info_help[16] = gengetopt_args_info_full_help[16];
  gengetopt_args_info_help[17] = gengetopt_args_info_full_help[17];
  gengetopt_args_info_help[18] = gengetopt_args_info_full_help[18];
  gengetopt_args_info_help[19] = gengetopt_args_info_full_help[19];
  gengetopt_args_info_help[20] = gengetopt_args_info_full_help[20];
  gengetopt_args_info_help[21] = gengetopt_args_info_full_help[21];
  gengetopt_args_info_help[22] = gengetopt_args_info_full_help[22];
  gengetopt_args_info_help[23] = gengetopt_args_info_full_help[25];
  gengetopt_args_info_help[24] = gengetopt_args_info_full_help[26];
  gengetopt_args_info_help[25] = gengetopt_args_info_full_help[30];
  gengetopt_args_info_help[26] = gengetopt_args_info_full_help[31];
  gengetopt_args_info_help[27] = gengetopt_args_info_full_help[32];
  gengetopt_args_info_help[28] = gengetopt_args_info_full_help[33];
  gengetopt_args_info_help[29] = gengetopt_args_info_full_help[34];
  gengetopt_args_info_help[30] = gengetopt_args_info_full_help[37];
  gengetopt_args_info_help[31] = gengetopt_args_info_full_help[38];
  gengetopt_args_info_help[32] = 0; 
  
}

const char *gengetopt_args_info_help[33];

typedef enum {ARG_NO
  , ARG_FLAG
  , ARG_STRING
  , ARG_INT
  , ARG_FLOAT
} cmdline_parser_arg_type;

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error);

static int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error);

static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->full_help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->noncomplementary_given = 0 ;
  args_info->param_given = 0 ;
  args_info->random_seed_given = 0 ;
  args_info->max_span_given = 0 ;
  args_info->verbose_given = 0 ;
  args_info->predict_given = 0 ;
  args_info->mea_given = 0 ;
  args_info->gce_given = 0 ;
  args_info->bpseq_given = 0 ;
  args_info->constraints_given = 0 ;
  args_info->train_given = 0 ;
  args_info->max_iter_given = 0 ;
  args_info->burn_in_given = 0 ;
  args_info->weight_weak_label_given = 0 ;
  args_info->structure_given = 0 ;
  args_info->unpaired_reactivity_given = 0 ;
  args_info->paired_reactivity_given = 0 ;
  args_info->both_reactivity_given = 0 ;
  args_info->eta_given = 0 ;
  args_info->eta_weak_label_given = 0 ;
  args_info->pos_w_given = 0 ;
  args_info->neg_w_given = 0 ;
  args_info->pos_w_unpaired_given = 0 ;
  args_info->neg_w_unpaired_given = 0 ;
  args_info->per_bp_loss_given = 0 ;
  args_info->lambda_given = 0 ;
  args_info->scale_reactivity_given = 0 ;
  args_info->threshold_unpaired_reactivity_given = 0 ;
  args_info->threshold_paired_reactivity_given = 0 ;
  args_info->discretize_reactivity_given = 0 ;
  args_info->bp_context_given = 0 ;
  args_info->out_param_given = 0 ;
  args_info->validate_given = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  FIX_UNUSED (args_info);
  args_info->noncomplementary_flag = 0;
  args_info->param_arg = NULL;
  args_info->param_orig = NULL;
  args_info->random_seed_arg = -1;
  args_info->random_seed_orig = NULL;
  args_info->max_span_arg = -1;
  args_info->max_span_orig = NULL;
  args_info->verbose_arg = 0;
  args_info->verbose_orig = NULL;
  args_info->predict_flag = 1;
  args_info->mea_arg = NULL;
  args_info->mea_orig = NULL;
  args_info->gce_arg = NULL;
  args_info->gce_orig = NULL;
  args_info->bpseq_flag = 0;
  args_info->constraints_flag = 0;
  args_info->train_arg = NULL;
  args_info->train_orig = NULL;
  args_info->max_iter_arg = 100;
  args_info->max_iter_orig = NULL;
  args_info->burn_in_arg = 10;
  args_info->burn_in_orig = NULL;
  args_info->weight_weak_label_arg = 0.1;
  args_info->weight_weak_label_orig = NULL;
  args_info->structure_arg = NULL;
  args_info->structure_orig = NULL;
  args_info->unpaired_reactivity_arg = NULL;
  args_info->unpaired_reactivity_orig = NULL;
  args_info->paired_reactivity_arg = NULL;
  args_info->paired_reactivity_orig = NULL;
  args_info->both_reactivity_arg = NULL;
  args_info->both_reactivity_orig = NULL;
  args_info->eta_arg = 1.0;
  args_info->eta_orig = NULL;
  args_info->eta_weak_label_arg = 0.1;
  args_info->eta_weak_label_orig = NULL;
  args_info->pos_w_arg = 8;
  args_info->pos_w_orig = NULL;
  args_info->neg_w_arg = 1;
  args_info->neg_w_orig = NULL;
  args_info->pos_w_unpaired_arg = 0;
  args_info->pos_w_unpaired_orig = NULL;
  args_info->neg_w_unpaired_arg = 0;
  args_info->neg_w_unpaired_orig = NULL;
  args_info->per_bp_loss_flag = 0;
  args_info->lambda_arg = 0.0001;
  args_info->lambda_orig = NULL;
  args_info->scale_reactivity_arg = 1.0;
  args_info->scale_reactivity_orig = NULL;
  args_info->threshold_unpaired_reactivity_arg = 0.0;
  args_info->threshold_unpaired_reactivity_orig = NULL;
  args_info->threshold_paired_reactivity_arg = 0.0;
  args_info->threshold_paired_reactivity_orig = NULL;
  args_info->discretize_reactivity_flag = 0;
  args_info->bp_context_flag = 0;
  args_info->out_param_arg = NULL;
  args_info->out_param_orig = NULL;
  args_info->validate_flag = 0;
  
}

static
void init_args_info(struct gengetopt_args_info *args_info)
{

  init_help_array(); 
  args_info->help_help = gengetopt_args_info_full_help[0] ;
  args_info->full_help_help = gengetopt_args_info_full_help[1] ;
  args_info->version_help = gengetopt_args_info_full_help[2] ;
  args_info->noncomplementary_help = gengetopt_args_info_full_help[3] ;
  args_info->param_help = gengetopt_args_info_full_help[4] ;
  args_info->random_seed_help = gengetopt_args_info_full_help[5] ;
  args_info->max_span_help = gengetopt_args_info_full_help[6] ;
  args_info->verbose_help = gengetopt_args_info_full_help[7] ;
  args_info->predict_help = gengetopt_args_info_full_help[9] ;
  args_info->mea_help = gengetopt_args_info_full_help[10] ;
  args_info->mea_min = 0;
  args_info->mea_max = 0;
  args_info->gce_help = gengetopt_args_info_full_help[11] ;
  args_info->gce_min = 0;
  args_info->gce_max = 0;
  args_info->bpseq_help = gengetopt_args_info_full_help[12] ;
  args_info->constraints_help = gengetopt_args_info_full_help[13] ;
  args_info->train_help = gengetopt_args_info_full_help[15] ;
  args_info->max_iter_help = gengetopt_args_info_full_help[16] ;
  args_info->burn_in_help = gengetopt_args_info_full_help[17] ;
  args_info->weight_weak_label_help = gengetopt_args_info_full_help[18] ;
  args_info->structure_help = gengetopt_args_info_full_help[19] ;
  args_info->structure_min = 0;
  args_info->structure_max = 0;
  args_info->unpaired_reactivity_help = gengetopt_args_info_full_help[20] ;
  args_info->unpaired_reactivity_min = 0;
  args_info->unpaired_reactivity_max = 0;
  args_info->paired_reactivity_help = gengetopt_args_info_full_help[21] ;
  args_info->paired_reactivity_min = 0;
  args_info->paired_reactivity_max = 0;
  args_info->both_reactivity_help = gengetopt_args_info_full_help[22] ;
  args_info->both_reactivity_min = 0;
  args_info->both_reactivity_max = 0;
  args_info->eta_help = gengetopt_args_info_full_help[23] ;
  args_info->eta_weak_label_help = gengetopt_args_info_full_help[24] ;
  args_info->pos_w_help = gengetopt_args_info_full_help[25] ;
  args_info->neg_w_help = gengetopt_args_info_full_help[26] ;
  args_info->pos_w_unpaired_help = gengetopt_args_info_full_help[27] ;
  args_info->neg_w_unpaired_help = gengetopt_args_info_full_help[28] ;
  args_info->per_bp_loss_help = gengetopt_args_info_full_help[29] ;
  args_info->lambda_help = gengetopt_args_info_full_help[30] ;
  args_info->scale_reactivity_help = gengetopt_args_info_full_help[31] ;
  args_info->threshold_unpaired_reactivity_help = gengetopt_args_info_full_help[32] ;
  args_info->threshold_paired_reactivity_help = gengetopt_args_info_full_help[33] ;
  args_info->discretize_reactivity_help = gengetopt_args_info_full_help[34] ;
  args_info->bp_context_help = gengetopt_args_info_full_help[35] ;
  args_info->out_param_help = gengetopt_args_info_full_help[36] ;
  args_info->validate_help = gengetopt_args_info_full_help[38] ;
  
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n",
     (strlen(CMDLINE_PARSER_PACKAGE_NAME) ? CMDLINE_PARSER_PACKAGE_NAME : CMDLINE_PARSER_PACKAGE),
     CMDLINE_PARSER_VERSION);

  if (strlen(gengetopt_args_info_versiontext) > 0)
    printf("\n%s\n", gengetopt_args_info_versiontext);
}

static void print_help_common(void) {
  cmdline_parser_print_version ();

  if (strlen(gengetopt_args_info_purpose) > 0)
    printf("\n%s\n", gengetopt_args_info_purpose);

  if (strlen(gengetopt_args_info_usage) > 0)
    printf("\n%s\n", gengetopt_args_info_usage);

  printf("\n");

  if (strlen(gengetopt_args_info_description) > 0)
    printf("%s\n\n", gengetopt_args_info_description);
}

void
cmdline_parser_print_help (void)
{
  int i = 0;
  print_help_common();
  while (gengetopt_args_info_help[i])
    printf("%s\n", gengetopt_args_info_help[i++]);
}

void
cmdline_parser_print_full_help (void)
{
  int i = 0;
  print_help_common();
  while (gengetopt_args_info_full_help[i])
    printf("%s\n", gengetopt_args_info_full_help[i++]);
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);

  args_info->inputs = 0;
  args_info->inputs_num = 0;
}

void
cmdline_parser_params_init(struct cmdline_parser_params *params)
{
  if (params)
    { 
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct cmdline_parser_params *
cmdline_parser_params_create(void)
{
  struct cmdline_parser_params *params = 
    (struct cmdline_parser_params *)malloc(sizeof(struct cmdline_parser_params));
  cmdline_parser_params_init(params);  
  return params;
}

static void
free_string_field (char **s)
{
  if (*s)
    {
      free (*s);
      *s = 0;
    }
}

/** @brief generic value variable */
union generic_value {
    int int_arg;
    float float_arg;
    char *string_arg;
    const char *default_string_arg;
};

/** @brief holds temporary values for multiple options */
struct generic_list
{
  union generic_value arg;
  char *orig;
  struct generic_list *next;
};

/**
 * @brief add a node at the head of the list 
 */
static void add_node(struct generic_list **list) {
  struct generic_list *new_node = (struct generic_list *) malloc (sizeof (struct generic_list));
  new_node->next = *list;
  *list = new_node;
  new_node->arg.string_arg = 0;
  new_node->orig = 0;
}

/**
 * The passed arg parameter is NOT set to 0 from this function
 */
static void
free_multiple_field(unsigned int len, void *arg, char ***orig)
{
  unsigned int i;
  if (arg) {
    for (i = 0; i < len; ++i)
      {
        free_string_field(&((*orig)[i]));
      }

    free (arg);
    free (*orig);
    *orig = 0;
  }
}

static void
free_multiple_string_field(unsigned int len, char ***arg, char ***orig)
{
  unsigned int i;
  if (*arg) {
    for (i = 0; i < len; ++i)
      {
        free_string_field(&((*arg)[i]));
        free_string_field(&((*orig)[i]));
      }
    free_string_field(&((*arg)[0])); /* free default string */

    free (*arg);
    *arg = 0;
    free (*orig);
    *orig = 0;
  }
}

static void
cmdline_parser_release (struct gengetopt_args_info *args_info)
{
  unsigned int i;
  free_string_field (&(args_info->param_arg));
  free_string_field (&(args_info->param_orig));
  free_string_field (&(args_info->random_seed_orig));
  free_string_field (&(args_info->max_span_orig));
  free_string_field (&(args_info->verbose_orig));
  free_multiple_field (args_info->mea_given, (void *)(args_info->mea_arg), &(args_info->mea_orig));
  args_info->mea_arg = 0;
  free_multiple_field (args_info->gce_given, (void *)(args_info->gce_arg), &(args_info->gce_orig));
  args_info->gce_arg = 0;
  free_string_field (&(args_info->train_arg));
  free_string_field (&(args_info->train_orig));
  free_string_field (&(args_info->max_iter_orig));
  free_string_field (&(args_info->burn_in_orig));
  free_string_field (&(args_info->weight_weak_label_orig));
  free_multiple_string_field (args_info->structure_given, &(args_info->structure_arg), &(args_info->structure_orig));
  free_multiple_string_field (args_info->unpaired_reactivity_given, &(args_info->unpaired_reactivity_arg), &(args_info->unpaired_reactivity_orig));
  free_multiple_string_field (args_info->paired_reactivity_given, &(args_info->paired_reactivity_arg), &(args_info->paired_reactivity_orig));
  free_multiple_string_field (args_info->both_reactivity_given, &(args_info->both_reactivity_arg), &(args_info->both_reactivity_orig));
  free_string_field (&(args_info->eta_orig));
  free_string_field (&(args_info->eta_weak_label_orig));
  free_string_field (&(args_info->pos_w_orig));
  free_string_field (&(args_info->neg_w_orig));
  free_string_field (&(args_info->pos_w_unpaired_orig));
  free_string_field (&(args_info->neg_w_unpaired_orig));
  free_string_field (&(args_info->lambda_orig));
  free_string_field (&(args_info->scale_reactivity_orig));
  free_string_field (&(args_info->threshold_unpaired_reactivity_orig));
  free_string_field (&(args_info->threshold_paired_reactivity_orig));
  free_string_field (&(args_info->out_param_arg));
  free_string_field (&(args_info->out_param_orig));
  
  
  for (i = 0; i < args_info->inputs_num; ++i)
    free (args_info->inputs [i]);

  if (args_info->inputs_num)
    free (args_info->inputs);

  clear_given (args_info);
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, const char *values[])
{
  FIX_UNUSED (values);
  if (arg) {
    fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}

static void
write_multiple_into_file(FILE *outfile, int len, const char *opt, char **arg, const char *values[])
{
  int i;
  
  for (i = 0; i < len; ++i)
    write_into_file(outfile, opt, (arg ? arg[i] : 0), values);
}

int
cmdline_parser_dump(FILE *outfile, struct gengetopt_args_info *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", CMDLINE_PARSER_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->help_given)
    write_into_file(outfile, "help", 0, 0 );
  if (args_info->full_help_given)
    write_into_file(outfile, "full-help", 0, 0 );
  if (args_info->version_given)
    write_into_file(outfile, "version", 0, 0 );
  if (args_info->noncomplementary_given)
    write_into_file(outfile, "noncomplementary", 0, 0 );
  if (args_info->param_given)
    write_into_file(outfile, "param", args_info->param_orig, 0);
  if (args_info->random_seed_given)
    write_into_file(outfile, "random-seed", args_info->random_seed_orig, 0);
  if (args_info->max_span_given)
    write_into_file(outfile, "max-span", args_info->max_span_orig, 0);
  if (args_info->verbose_given)
    write_into_file(outfile, "verbose", args_info->verbose_orig, 0);
  if (args_info->predict_given)
    write_into_file(outfile, "predict", 0, 0 );
  write_multiple_into_file(outfile, args_info->mea_given, "mea", args_info->mea_orig, 0);
  write_multiple_into_file(outfile, args_info->gce_given, "gce", args_info->gce_orig, 0);
  if (args_info->bpseq_given)
    write_into_file(outfile, "bpseq", 0, 0 );
  if (args_info->constraints_given)
    write_into_file(outfile, "constraints", 0, 0 );
  if (args_info->train_given)
    write_into_file(outfile, "train", args_info->train_orig, 0);
  if (args_info->max_iter_given)
    write_into_file(outfile, "max-iter", args_info->max_iter_orig, 0);
  if (args_info->burn_in_given)
    write_into_file(outfile, "burn-in", args_info->burn_in_orig, 0);
  if (args_info->weight_weak_label_given)
    write_into_file(outfile, "weight-weak-label", args_info->weight_weak_label_orig, 0);
  write_multiple_into_file(outfile, args_info->structure_given, "structure", args_info->structure_orig, 0);
  write_multiple_into_file(outfile, args_info->unpaired_reactivity_given, "unpaired-reactivity", args_info->unpaired_reactivity_orig, 0);
  write_multiple_into_file(outfile, args_info->paired_reactivity_given, "paired-reactivity", args_info->paired_reactivity_orig, 0);
  write_multiple_into_file(outfile, args_info->both_reactivity_given, "both-reactivity", args_info->both_reactivity_orig, 0);
  if (args_info->eta_given)
    write_into_file(outfile, "eta", args_info->eta_orig, 0);
  if (args_info->eta_weak_label_given)
    write_into_file(outfile, "eta-weak-label", args_info->eta_weak_label_orig, 0);
  if (args_info->pos_w_given)
    write_into_file(outfile, "pos-w", args_info->pos_w_orig, 0);
  if (args_info->neg_w_given)
    write_into_file(outfile, "neg-w", args_info->neg_w_orig, 0);
  if (args_info->pos_w_unpaired_given)
    write_into_file(outfile, "pos-w-unpaired", args_info->pos_w_unpaired_orig, 0);
  if (args_info->neg_w_unpaired_given)
    write_into_file(outfile, "neg-w-unpaired", args_info->neg_w_unpaired_orig, 0);
  if (args_info->per_bp_loss_given)
    write_into_file(outfile, "per-bp-loss", 0, 0 );
  if (args_info->lambda_given)
    write_into_file(outfile, "lambda", args_info->lambda_orig, 0);
  if (args_info->scale_reactivity_given)
    write_into_file(outfile, "scale-reactivity", args_info->scale_reactivity_orig, 0);
  if (args_info->threshold_unpaired_reactivity_given)
    write_into_file(outfile, "threshold-unpaired-reactivity", args_info->threshold_unpaired_reactivity_orig, 0);
  if (args_info->threshold_paired_reactivity_given)
    write_into_file(outfile, "threshold-paired-reactivity", args_info->threshold_paired_reactivity_orig, 0);
  if (args_info->discretize_reactivity_given)
    write_into_file(outfile, "discretize-reactivity", 0, 0 );
  if (args_info->bp_context_given)
    write_into_file(outfile, "bp-context", 0, 0 );
  if (args_info->out_param_given)
    write_into_file(outfile, "out-param", args_info->out_param_orig, 0);
  if (args_info->validate_given)
    write_into_file(outfile, "validate", 0, 0 );
  

  i = EXIT_SUCCESS;
  return i;
}

int
cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = cmdline_parser_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  cmdline_parser_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = 0;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

static char *
get_multiple_arg_token(const char *arg)
{
  const char *tok;
  char *ret;
  size_t len, num_of_escape, i, j;

  if (!arg)
    return 0;

  tok = strchr (arg, ',');
  num_of_escape = 0;

  /* make sure it is not escaped */
  while (tok)
    {
      if (*(tok-1) == '\\')
        {
          /* find the next one */
          tok = strchr (tok+1, ',');
          ++num_of_escape;
        }
      else
        break;
    }

  if (tok)
    len = (size_t)(tok - arg + 1);
  else
    len = strlen (arg) + 1;

  len -= num_of_escape;

  ret = (char *) malloc (len);

  i = 0;
  j = 0;
  while (arg[i] && (j < len-1))
    {
      if (arg[i] == '\\' && 
	  arg[ i + 1 ] && 
	  arg[ i + 1 ] == ',')
        ++i;

      ret[j++] = arg[i++];
    }

  ret[len-1] = '\0';

  return ret;
}

static const char *
get_multiple_arg_token_next(const char *arg)
{
  const char *tok;

  if (!arg)
    return 0;

  tok = strchr (arg, ',');

  /* make sure it is not escaped */
  while (tok)
    {
      if (*(tok-1) == '\\')
        {
          /* find the next one */
          tok = strchr (tok+1, ',');
        }
      else
        break;
    }

  if (! tok || strlen(tok) == 1)
    return 0;

  return tok+1;
}

static int
check_multiple_option_occurrences(const char *prog_name, unsigned int option_given, unsigned int min, unsigned int max, const char *option_desc);

int
check_multiple_option_occurrences(const char *prog_name, unsigned int option_given, unsigned int min, unsigned int max, const char *option_desc)
{
  int error_occurred = 0;

  if (option_given && (min > 0 || max > 0))
    {
      if (min > 0 && max > 0)
        {
          if (min == max)
            {
              /* specific occurrences */
              if (option_given != (unsigned int) min)
                {
                  fprintf (stderr, "%s: %s option occurrences must be %d\n",
                    prog_name, option_desc, min);
                  error_occurred = 1;
                }
            }
          else if (option_given < (unsigned int) min
                || option_given > (unsigned int) max)
            {
              /* range occurrences */
              fprintf (stderr, "%s: %s option occurrences must be between %d and %d\n",
                prog_name, option_desc, min, max);
              error_occurred = 1;
            }
        }
      else if (min > 0)
        {
          /* at least check */
          if (option_given < min)
            {
              fprintf (stderr, "%s: %s option occurrences must be at least %d\n",
                prog_name, option_desc, min);
              error_occurred = 1;
            }
        }
      else if (max > 0)
        {
          /* at most check */
          if (option_given > max)
            {
              fprintf (stderr, "%s: %s option occurrences must be at most %d\n",
                prog_name, option_desc, max);
              error_occurred = 1;
            }
        }
    }
    
  return error_occurred;
}
int
cmdline_parser (int argc, char **argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser_ext (int argc, char **argv, struct gengetopt_args_info *args_info,
                   struct cmdline_parser_params *params)
{
  int result;
  result = cmdline_parser_internal (argc, argv, args_info, params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser2 (int argc, char **argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;
  struct cmdline_parser_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = cmdline_parser_internal (argc, argv, args_info, &params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  int result = EXIT_SUCCESS;

  if (cmdline_parser_required2(args_info, prog_name, 0) > 0)
    result = EXIT_FAILURE;

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error)
{
  int error_occurred = 0;
  FIX_UNUSED (additional_error);

  /* checks for required options */
  if (check_multiple_option_occurrences(prog_name, args_info->mea_given, args_info->mea_min, args_info->mea_max, "'--mea'"))
     error_occurred = 1;
  
  if (check_multiple_option_occurrences(prog_name, args_info->gce_given, args_info->gce_min, args_info->gce_max, "'--gce' ('-g')"))
     error_occurred = 1;
  
  if (check_multiple_option_occurrences(prog_name, args_info->structure_given, args_info->structure_min, args_info->structure_max, "'--structure' ('-T')"))
     error_occurred = 1;
  
  if (check_multiple_option_occurrences(prog_name, args_info->unpaired_reactivity_given, args_info->unpaired_reactivity_min, args_info->unpaired_reactivity_max, "'--unpaired-reactivity' ('-U')"))
     error_occurred = 1;
  
  if (check_multiple_option_occurrences(prog_name, args_info->paired_reactivity_given, args_info->paired_reactivity_min, args_info->paired_reactivity_max, "'--paired-reactivity' ('-P')"))
     error_occurred = 1;
  
  if (check_multiple_option_occurrences(prog_name, args_info->both_reactivity_given, args_info->both_reactivity_min, args_info->both_reactivity_max, "'--both-reactivity' ('-B')"))
     error_occurred = 1;
  
  
  /* checks for dependences among options */

  return error_occurred;
}


static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see cmdline_parser_params.check_ambiguity
 * @param override @see cmdline_parser_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static
int update_arg(void *field, char **orig_field,
               unsigned int *field_given, unsigned int *prev_given, 
               char *value, const char *possible_values[],
               const char *default_value,
               cmdline_parser_arg_type arg_type,
               int check_ambiguity, int override,
               int no_free, int multiple_option,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  char *stop_char = 0;
  const char *val = value;
  int found;
  char **string_field;
  FIX_UNUSED (field);

  stop_char = 0;
  found = 0;

  if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given)))
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: `--%s' (`-%c') option given more than once%s\n", 
               package_name, long_opt, short_opt,
               (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: `--%s' option given more than once%s\n", 
               package_name, long_opt,
               (additional_error ? additional_error : ""));
      return 1; /* failure */
    }

  FIX_UNUSED (default_value);
    
  if (field_given && *field_given && ! override)
    return 0;
  if (prev_given)
    (*prev_given)++;
  if (field_given)
    (*field_given)++;
  if (possible_values)
    val = possible_values[found];

  switch(arg_type) {
  case ARG_FLAG:
    *((int *)field) = !*((int *)field);
    break;
  case ARG_INT:
    if (val) *((int *)field) = strtol (val, &stop_char, 0);
    break;
  case ARG_FLOAT:
    if (val) *((float *)field) = (float)strtod (val, &stop_char);
    break;
  case ARG_STRING:
    if (val) {
      string_field = (char **)field;
      if (!no_free && *string_field)
        free (*string_field); /* free previous string */
      *string_field = gengetopt_strdup (val);
    }
    break;
  default:
    break;
  };

  /* check numeric conversion */
  switch(arg_type) {
  case ARG_INT:
  case ARG_FLOAT:
    if (val && !(stop_char && *stop_char == '\0')) {
      fprintf(stderr, "%s: invalid numeric value: %s\n", package_name, val);
      return 1; /* failure */
    }
    break;
  default:
    ;
  };

  /* store the original value */
  switch(arg_type) {
  case ARG_NO:
  case ARG_FLAG:
    break;
  default:
    if (value && orig_field) {
      if (no_free) {
        *orig_field = value;
      } else {
        if (*orig_field)
          free (*orig_field); /* free previous string */
        *orig_field = gengetopt_strdup (value);
      }
    }
  };

  return 0; /* OK */
}

/**
 * @brief store information about a multiple option in a temporary list
 * @param list where to (temporarily) store multiple options
 */
static
int update_multiple_arg_temp(struct generic_list **list,
               unsigned int *prev_given, const char *val,
               const char *possible_values[], const char *default_value,
               cmdline_parser_arg_type arg_type,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  /* store single arguments */
  char *multi_token;
  const char *multi_next;

  if (arg_type == ARG_NO) {
    (*prev_given)++;
    return 0; /* OK */
  }

  multi_token = get_multiple_arg_token(val);
  multi_next = get_multiple_arg_token_next (val);

  while (1)
    {
      add_node (list);
      if (update_arg((void *)&((*list)->arg), &((*list)->orig), 0,
          prev_given, multi_token, possible_values, default_value, 
          arg_type, 0, 1, 1, 1, long_opt, short_opt, additional_error)) {
        if (multi_token) free(multi_token);
        return 1; /* failure */
      }

      if (multi_next)
        {
          multi_token = get_multiple_arg_token(multi_next);
          multi_next = get_multiple_arg_token_next (multi_next);
        }
      else
        break;
    }

  return 0; /* OK */
}

/**
 * @brief free the passed list (including possible string argument)
 */
static
void free_list(struct generic_list *list, short string_arg)
{
  if (list) {
    struct generic_list *tmp;
    while (list)
      {
        tmp = list;
        if (string_arg && list->arg.string_arg)
          free (list->arg.string_arg);
        if (list->orig)
          free (list->orig);
        list = list->next;
        free (tmp);
      }
  }
}

/**
 * @brief updates a multiple option starting from the passed list
 */
static
void update_multiple_arg(void *field, char ***orig_field,
               unsigned int field_given, unsigned int prev_given, union generic_value *default_value,
               cmdline_parser_arg_type arg_type,
               struct generic_list *list)
{
  int i;
  struct generic_list *tmp;

  if (prev_given && list) {
    *orig_field = (char **) realloc (*orig_field, (field_given + prev_given) * sizeof (char *));

    switch(arg_type) {
    case ARG_INT:
      *((int **)field) = (int *)realloc (*((int **)field), (field_given + prev_given) * sizeof (int)); break;
    case ARG_FLOAT:
      *((float **)field) = (float *)realloc (*((float **)field), (field_given + prev_given) * sizeof (float)); break;
    case ARG_STRING:
      *((char ***)field) = (char **)realloc (*((char ***)field), (field_given + prev_given) * sizeof (char *)); break;
    default:
      break;
    };
    
    for (i = (prev_given - 1); i >= 0; --i)
      {
        tmp = list;
        
        switch(arg_type) {
        case ARG_INT:
          (*((int **)field))[i + field_given] = tmp->arg.int_arg; break;
        case ARG_FLOAT:
          (*((float **)field))[i + field_given] = tmp->arg.float_arg; break;
        case ARG_STRING:
          (*((char ***)field))[i + field_given] = tmp->arg.string_arg; break;
        default:
          break;
        }        
        (*orig_field) [i + field_given] = list->orig;
        list = list->next;
        free (tmp);
      }
  } else { /* set the default value */
    if (default_value && ! field_given) {
      switch(arg_type) {
      case ARG_INT:
        if (! *((int **)field)) {
          *((int **)field) = (int *)malloc (sizeof (int));
          (*((int **)field))[0] = default_value->int_arg; 
        }
        break;
      case ARG_FLOAT:
        if (! *((float **)field)) {
          *((float **)field) = (float *)malloc (sizeof (float));
          (*((float **)field))[0] = default_value->float_arg;
        }
        break;
      case ARG_STRING:
        if (! *((char ***)field)) {
          *((char ***)field) = (char **)malloc (sizeof (char *));
          (*((char ***)field))[0] = gengetopt_strdup(default_value->string_arg);
        }
        break;
      default: break;
      }
      if (!(*orig_field)) {
        *orig_field = (char **) malloc (sizeof (char *));
        (*orig_field)[0] = 0;
      }
    }
  }
}

int
cmdline_parser_internal (
  int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */
  union generic_value multiple_default_value;

  struct generic_list * mea_list = NULL;
  struct generic_list * gce_list = NULL;
  struct generic_list * structure_list = NULL;
  struct generic_list * unpaired_reactivity_list = NULL;
  struct generic_list * paired_reactivity_list = NULL;
  struct generic_list * both_reactivity_list = NULL;
  int error_occurred = 0;
  struct gengetopt_args_info local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;
  
  package_name = argv[0];
  
  override = params->override;
  initialize = params->initialize;
  check_required = params->check_required;
  check_ambiguity = params->check_ambiguity;

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "full-help",	0, NULL, 0 },
        { "version",	0, NULL, 'V' },
        { "noncomplementary",	0, NULL, 0 },
        { "param",	1, NULL, 'p' },
        { "random-seed",	1, NULL, 0 },
        { "max-span",	1, NULL, 0 },
        { "verbose",	1, NULL, 'v' },
        { "predict",	0, NULL, 0 },
        { "mea",	1, NULL, 0 },
        { "gce",	1, NULL, 'g' },
        { "bpseq",	0, NULL, 0 },
        { "constraints",	0, NULL, 0 },
        { "train",	1, NULL, 0 },
        { "max-iter",	1, NULL, 'i' },
        { "burn-in",	1, NULL, 'b' },
        { "weight-weak-label",	1, NULL, 0 },
        { "structure",	1, NULL, 'T' },
        { "unpaired-reactivity",	1, NULL, 'U' },
        { "paired-reactivity",	1, NULL, 'P' },
        { "both-reactivity",	1, NULL, 'B' },
        { "eta",	1, NULL, 0 },
        { "eta-weak-label",	1, NULL, 0 },
        { "pos-w",	1, NULL, 0 },
        { "neg-w",	1, NULL, 0 },
        { "pos-w-unpaired",	1, NULL, 0 },
        { "neg-w-unpaired",	1, NULL, 0 },
        { "per-bp-loss",	0, NULL, 0 },
        { "lambda",	1, NULL, 0 },
        { "scale-reactivity",	1, NULL, 0 },
        { "threshold-unpaired-reactivity",	1, NULL, 0 },
        { "threshold-paired-reactivity",	1, NULL, 0 },
        { "discretize-reactivity",	0, NULL, 0 },
        { "bp-context",	0, NULL, 0 },
        { "out-param",	1, NULL, 0 },
        { "validate",	0, NULL, 0 },
        { 0,  0, 0, 0 }
      };

      c = getopt_long (argc, argv, "hVp:v:g:i:b:T:U:P:B:", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          cmdline_parser_print_version ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'p':	/* Load parameters from parameter-file.  */
        
        
          if (update_arg( (void *)&(args_info->param_arg), 
               &(args_info->param_orig), &(args_info->param_given),
              &(local_args_info.param_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "param", 'p',
              additional_error))
            goto failure;
        
          break;
        case 'v':	/* Verbose output.  */
        
        
          if (update_arg( (void *)&(args_info->verbose_arg), 
               &(args_info->verbose_orig), &(args_info->verbose_given),
              &(local_args_info.verbose_given), optarg, 0, "0", ARG_INT,
              check_ambiguity, override, 0, 0,
              "verbose", 'v',
              additional_error))
            goto failure;
        
          break;
        case 'g':	/* Generalized centroid decoding with gamma.  */
        
          if (update_multiple_arg_temp(&gce_list, 
              &(local_args_info.gce_given), optarg, 0, "4.0", ARG_FLOAT,
              "gce", 'g',
              additional_error))
            goto failure;
        
          break;
        case 'i':	/* The maximum number of iterations for training.  */
        
        
          if (update_arg( (void *)&(args_info->max_iter_arg), 
               &(args_info->max_iter_orig), &(args_info->max_iter_given),
              &(local_args_info.max_iter_given), optarg, 0, "100", ARG_INT,
              check_ambiguity, override, 0, 0,
              "max-iter", 'i',
              additional_error))
            goto failure;
        
          break;
        case 'b':	/* The number of iterations for initial training from labeled data.  */
        
        
          if (update_arg( (void *)&(args_info->burn_in_arg), 
               &(args_info->burn_in_orig), &(args_info->burn_in_given),
              &(local_args_info.burn_in_given), optarg, 0, "10", ARG_INT,
              check_ambiguity, override, 0, 0,
              "burn-in", 'b',
              additional_error))
            goto failure;
        
          break;
        case 'T':	/* The lists of training data with full structures.  */
        
          if (update_multiple_arg_temp(&structure_list, 
              &(local_args_info.structure_given), optarg, 0, 0, ARG_STRING,
              "structure", 'T',
              additional_error))
            goto failure;
        
          break;
        case 'U':	/* The lists of training data with unpaired reactivity.  */
        
          if (update_multiple_arg_temp(&unpaired_reactivity_list, 
              &(local_args_info.unpaired_reactivity_given), optarg, 0, 0, ARG_STRING,
              "unpaired-reactivity", 'U',
              additional_error))
            goto failure;
        
          break;
        case 'P':	/* The lists of training data with paired reactivity.  */
        
          if (update_multiple_arg_temp(&paired_reactivity_list, 
              &(local_args_info.paired_reactivity_given), optarg, 0, 0, ARG_STRING,
              "paired-reactivity", 'P',
              additional_error))
            goto failure;
        
          break;
        case 'B':	/* The lists of training data with both of unpaired and paired  reactivity.  */
        
          if (update_multiple_arg_temp(&both_reactivity_list, 
              &(local_args_info.both_reactivity_given), optarg, 0, 0, ARG_STRING,
              "both-reactivity", 'B',
              additional_error))
            goto failure;
        
          break;

        case 0:	/* Long option with no short option */
          if (strcmp (long_options[option_index].name, "full-help") == 0) {
            cmdline_parser_print_full_help ();
            cmdline_parser_free (&local_args_info);
            exit (EXIT_SUCCESS);
          }

          /* Allow non-canonical base pairs.  */
          if (strcmp (long_options[option_index].name, "noncomplementary") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->noncomplementary_flag), 0, &(args_info->noncomplementary_given),
                &(local_args_info.noncomplementary_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "noncomplementary", '-',
                additional_error))
              goto failure;
          
          }
          /* Specify the seed of the random number generator.  */
          else if (strcmp (long_options[option_index].name, "random-seed") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->random_seed_arg), 
                 &(args_info->random_seed_orig), &(args_info->random_seed_given),
                &(local_args_info.random_seed_given), optarg, 0, "-1", ARG_INT,
                check_ambiguity, override, 0, 0,
                "random-seed", '-',
                additional_error))
              goto failure;
          
          }
          /* The maximum distance between bases of base pairs.  */
          else if (strcmp (long_options[option_index].name, "max-span") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->max_span_arg), 
                 &(args_info->max_span_orig), &(args_info->max_span_given),
                &(local_args_info.max_span_given), optarg, 0, "-1", ARG_INT,
                check_ambiguity, override, 0, 0,
                "max-span", '-',
                additional_error))
              goto failure;
          
          }
          /* Prediction mode.  */
          else if (strcmp (long_options[option_index].name, "predict") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->predict_flag), 0, &(args_info->predict_given),
                &(local_args_info.predict_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "predict", '-',
                additional_error))
              goto failure;
          
          }
          /* MEA decoding with gamma.  */
          else if (strcmp (long_options[option_index].name, "mea") == 0)
          {
          
            if (update_multiple_arg_temp(&mea_list, 
                &(local_args_info.mea_given), optarg, 0, "6.0", ARG_FLOAT,
                "mea", '-',
                additional_error))
              goto failure;
          
          }
          /* Output predicted results as the BPSEQ format.  */
          else if (strcmp (long_options[option_index].name, "bpseq") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->bpseq_flag), 0, &(args_info->bpseq_given),
                &(local_args_info.bpseq_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "bpseq", '-',
                additional_error))
              goto failure;
          
          }
          /* Use contraints.  */
          else if (strcmp (long_options[option_index].name, "constraints") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->constraints_flag), 0, &(args_info->constraints_given),
                &(local_args_info.constraints_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "constraints", '-',
                additional_error))
              goto failure;
          
          }
          /* Trainining mode (write the trained parameters into output-file).  */
          else if (strcmp (long_options[option_index].name, "train") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->train_arg), 
                 &(args_info->train_orig), &(args_info->train_given),
                &(local_args_info.train_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "train", '-',
                additional_error))
              goto failure;
          
          }
          /* The weight for weak labeled data.  */
          else if (strcmp (long_options[option_index].name, "weight-weak-label") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->weight_weak_label_arg), 
                 &(args_info->weight_weak_label_orig), &(args_info->weight_weak_label_given),
                &(local_args_info.weight_weak_label_given), optarg, 0, "0.1", ARG_FLOAT,
                check_ambiguity, override, 0, 0,
                "weight-weak-label", '-',
                additional_error))
              goto failure;
          
          }
          /* Initial step width of the subgradient optimization.  */
          else if (strcmp (long_options[option_index].name, "eta") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->eta_arg), 
                 &(args_info->eta_orig), &(args_info->eta_given),
                &(local_args_info.eta_given), optarg, 0, "1.0", ARG_FLOAT,
                check_ambiguity, override, 0, 0,
                "eta", '-',
                additional_error))
              goto failure;
          
          }
          /* Initial step width of the subgradient optimization for weak labeled data.  */
          else if (strcmp (long_options[option_index].name, "eta-weak-label") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->eta_weak_label_arg), 
                 &(args_info->eta_weak_label_orig), &(args_info->eta_weak_label_given),
                &(local_args_info.eta_weak_label_given), optarg, 0, "0.1", ARG_FLOAT,
                check_ambiguity, override, 0, 0,
                "eta-weak-label", '-',
                additional_error))
              goto failure;
          
          }
          /* The weight for positive base-pairs.  */
          else if (strcmp (long_options[option_index].name, "pos-w") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->pos_w_arg), 
                 &(args_info->pos_w_orig), &(args_info->pos_w_given),
                &(local_args_info.pos_w_given), optarg, 0, "8", ARG_FLOAT,
                check_ambiguity, override, 0, 0,
                "pos-w", '-',
                additional_error))
              goto failure;
          
          }
          /* The weight for negative base-pairs.  */
          else if (strcmp (long_options[option_index].name, "neg-w") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->neg_w_arg), 
                 &(args_info->neg_w_orig), &(args_info->neg_w_given),
                &(local_args_info.neg_w_given), optarg, 0, "1", ARG_FLOAT,
                check_ambiguity, override, 0, 0,
                "neg-w", '-',
                additional_error))
              goto failure;
          
          }
          /* The weight for positive base-pairs for training from unpaired reactivity data.  */
          else if (strcmp (long_options[option_index].name, "pos-w-unpaired") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->pos_w_unpaired_arg), 
                 &(args_info->pos_w_unpaired_orig), &(args_info->pos_w_unpaired_given),
                &(local_args_info.pos_w_unpaired_given), optarg, 0, "0", ARG_FLOAT,
                check_ambiguity, override, 0, 0,
                "pos-w-unpaired", '-',
                additional_error))
              goto failure;
          
          }
          /* The weight for negative base-pairs for training from unpaired reactivity data.  */
          else if (strcmp (long_options[option_index].name, "neg-w-unpaired") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->neg_w_unpaired_arg), 
                 &(args_info->neg_w_unpaired_orig), &(args_info->neg_w_unpaired_given),
                &(local_args_info.neg_w_unpaired_given), optarg, 0, "0", ARG_FLOAT,
                check_ambiguity, override, 0, 0,
                "neg-w-unpaired", '-',
                additional_error))
              goto failure;
          
          }
          /* Ajust the loss according to the number of base pairs.  */
          else if (strcmp (long_options[option_index].name, "per-bp-loss") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->per_bp_loss_flag), 0, &(args_info->per_bp_loss_given),
                &(local_args_info.per_bp_loss_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "per-bp-loss", '-',
                additional_error))
              goto failure;
          
          }
          /* The weight for the L1 regularization term.  */
          else if (strcmp (long_options[option_index].name, "lambda") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->lambda_arg), 
                 &(args_info->lambda_orig), &(args_info->lambda_given),
                &(local_args_info.lambda_given), optarg, 0, "0.0001", ARG_FLOAT,
                check_ambiguity, override, 0, 0,
                "lambda", '-',
                additional_error))
              goto failure;
          
          }
          /* The scale of reactivity.  */
          else if (strcmp (long_options[option_index].name, "scale-reactivity") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->scale_reactivity_arg), 
                 &(args_info->scale_reactivity_orig), &(args_info->scale_reactivity_given),
                &(local_args_info.scale_reactivity_given), optarg, 0, "1.0", ARG_FLOAT,
                check_ambiguity, override, 0, 0,
                "scale-reactivity", '-',
                additional_error))
              goto failure;
          
          }
          /* The threshold of reactiviy for unpaired bases.  */
          else if (strcmp (long_options[option_index].name, "threshold-unpaired-reactivity") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->threshold_unpaired_reactivity_arg), 
                 &(args_info->threshold_unpaired_reactivity_orig), &(args_info->threshold_unpaired_reactivity_given),
                &(local_args_info.threshold_unpaired_reactivity_given), optarg, 0, "0.0", ARG_FLOAT,
                check_ambiguity, override, 0, 0,
                "threshold-unpaired-reactivity", '-',
                additional_error))
              goto failure;
          
          }
          /* The threshold of reactiviy for paired bases.  */
          else if (strcmp (long_options[option_index].name, "threshold-paired-reactivity") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->threshold_paired_reactivity_arg), 
                 &(args_info->threshold_paired_reactivity_orig), &(args_info->threshold_paired_reactivity_given),
                &(local_args_info.threshold_paired_reactivity_given), optarg, 0, "0.0", ARG_FLOAT,
                check_ambiguity, override, 0, 0,
                "threshold-paired-reactivity", '-',
                additional_error))
              goto failure;
          
          }
          /* Discretize reactivity with reactivity thresholds.  */
          else if (strcmp (long_options[option_index].name, "discretize-reactivity") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->discretize_reactivity_flag), 0, &(args_info->discretize_reactivity_given),
                &(local_args_info.discretize_reactivity_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "discretize-reactivity", '-',
                additional_error))
              goto failure;
          
          }
          /* Train the features for base-pair contexts in weak label traing .  */
          else if (strcmp (long_options[option_index].name, "bp-context") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->bp_context_flag), 0, &(args_info->bp_context_given),
                &(local_args_info.bp_context_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "bp-context", '-',
                additional_error))
              goto failure;
          
          }
          /* Output parameter sets for each step.  */
          else if (strcmp (long_options[option_index].name, "out-param") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->out_param_arg), 
                 &(args_info->out_param_orig), &(args_info->out_param_given),
                &(local_args_info.out_param_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "out-param", '-',
                additional_error))
              goto failure;
          
          }
          /* Validation mode: validate the given structure can be parsed.  */
          else if (strcmp (long_options[option_index].name, "validate") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->validate_flag), 0, &(args_info->validate_given),
                &(local_args_info.validate_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "validate", '-',
                additional_error))
              goto failure;
          
          }
          
          break;
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */


  multiple_default_value.float_arg = 6.0;
  update_multiple_arg((void *)&(args_info->mea_arg),
    &(args_info->mea_orig), args_info->mea_given,
    local_args_info.mea_given, &multiple_default_value,
    ARG_FLOAT, mea_list);
  multiple_default_value.float_arg = 4.0;
  update_multiple_arg((void *)&(args_info->gce_arg),
    &(args_info->gce_orig), args_info->gce_given,
    local_args_info.gce_given, &multiple_default_value,
    ARG_FLOAT, gce_list);
  update_multiple_arg((void *)&(args_info->structure_arg),
    &(args_info->structure_orig), args_info->structure_given,
    local_args_info.structure_given, 0,
    ARG_STRING, structure_list);
  update_multiple_arg((void *)&(args_info->unpaired_reactivity_arg),
    &(args_info->unpaired_reactivity_orig), args_info->unpaired_reactivity_given,
    local_args_info.unpaired_reactivity_given, 0,
    ARG_STRING, unpaired_reactivity_list);
  update_multiple_arg((void *)&(args_info->paired_reactivity_arg),
    &(args_info->paired_reactivity_orig), args_info->paired_reactivity_given,
    local_args_info.paired_reactivity_given, 0,
    ARG_STRING, paired_reactivity_list);
  update_multiple_arg((void *)&(args_info->both_reactivity_arg),
    &(args_info->both_reactivity_orig), args_info->both_reactivity_given,
    local_args_info.both_reactivity_given, 0,
    ARG_STRING, both_reactivity_list);

  args_info->mea_given += local_args_info.mea_given;
  local_args_info.mea_given = 0;
  args_info->gce_given += local_args_info.gce_given;
  local_args_info.gce_given = 0;
  args_info->structure_given += local_args_info.structure_given;
  local_args_info.structure_given = 0;
  args_info->unpaired_reactivity_given += local_args_info.unpaired_reactivity_given;
  local_args_info.unpaired_reactivity_given = 0;
  args_info->paired_reactivity_given += local_args_info.paired_reactivity_given;
  local_args_info.paired_reactivity_given = 0;
  args_info->both_reactivity_given += local_args_info.both_reactivity_given;
  local_args_info.both_reactivity_given = 0;
  
  if (check_required)
    {
      error_occurred += cmdline_parser_required2 (args_info, argv[0], additional_error);
    }

  cmdline_parser_release (&local_args_info);

  if ( error_occurred )
    return (EXIT_FAILURE);

  if (optind < argc)
    {
      int i = 0 ;
      int found_prog_name = 0;
      /* whether program name, i.e., argv[0], is in the remaining args
         (this may happen with some implementations of getopt,
          but surely not with the one included by gengetopt) */

      i = optind;
      while (i < argc)
        if (argv[i++] == argv[0]) {
          found_prog_name = 1;
          break;
        }
      i = 0;

      args_info->inputs_num = argc - optind - found_prog_name;
      args_info->inputs =
        (char **)(malloc ((args_info->inputs_num)*sizeof(char *))) ;
      while (optind < argc)
        if (argv[optind++] != argv[0])
          args_info->inputs[ i++ ] = gengetopt_strdup (argv[optind-1]) ;
    }

  return 0;

failure:
  free_list (mea_list, 0 );
  free_list (gce_list, 0 );
  free_list (structure_list, 1 );
  free_list (unpaired_reactivity_list, 1 );
  free_list (paired_reactivity_list, 1 );
  free_list (both_reactivity_list, 1 );
  
  cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
